-- Enable Row Level Security
ALTER TABLE IF EXISTS profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS student_data ENABLE ROW LEVEL SECURITY;

-- Profiles table to store user roles and metadata
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT CHECK (role IN ('Admin', 'Student', 'Teacher')) DEFAULT 'Student',
    roll_no TEXT UNIQUE,
    password_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Student data table
CREATE TABLE IF NOT EXISTS student_data (
    roll_no TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    study_hours FLOAT,
    attendance FLOAT,
    motivation TEXT,
    learning_style TEXT,
    stress_level FLOAT,
    sem1_marks FLOAT DEFAULT 0,
    sem2_marks FLOAT DEFAULT 0,
    sem3_marks FLOAT DEFAULT 0,
    sem4_marks FLOAT DEFAULT 0,
    total_marks FLOAT DEFAULT 0,
    average FLOAT DEFAULT 0,
    momentum FLOAT DEFAULT 0,
    predicted_grade FLOAT,
    risk_level TEXT CHECK (risk_level IN ('High Risk', 'Average', 'Low Risk')),
    is_at_risk BOOLEAN DEFAULT FALSE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alerts log
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_no TEXT REFERENCES student_data(roll_no) ON DELETE CASCADE,
    student_name TEXT,
    risk_factor TEXT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Functions and Triggers

-- Trigger to update momentum and total marks on change
CREATE OR REPLACE FUNCTION calculate_student_metrics()
RETURNS TRIGGER AS $$
BEGIN
    NEW.total_marks := NEW.sem1_marks + NEW.sem2_marks + NEW.sem3_marks + NEW.sem4_marks;
    NEW.average := NEW.total_marks / 4.0;
    -- Academic Momentum Slope: (3*S4 + S3 - S2 - 3*S1) / 10
    NEW.momentum := (1.5 * NEW.sem4_marks + 0.5 * NEW.sem3_marks - 0.5 * NEW.sem2_marks - 1.5 * NEW.sem1_marks) / 5.0;
    
    NEW.last_updated := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_calculate_metrics
BEFORE INSERT OR UPDATE ON student_data
FOR EACH ROW
EXECUTE FUNCTION calculate_student_metrics();

-- RLS Policies (Simplified for local setup)
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Student data is viewable by admins and the student themselves." 
ON student_data FOR SELECT 
USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'Admin')
    OR (roll_no = (SELECT roll_no FROM profiles WHERE id = auth.uid()))
);
